In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import os
import time
import pandas as pd
import pickle
repoDir= os.getcwd()
os.chdir(os.path.join(repoDir , '..' ))
repoDir= os.getcwd()

In [2]:
filenames= [f for f in os.listdir('chipsPerVisitData/') if any([f.endswith('pickle')])]
savedData= {}

for filename in filenames:
    splits= filename.split('_')
    if (len(splits)==8):
        key= splits[4]+'_'+splits[5]
    else:
        key= splits[4]
    with open('chipsPerVisitData/'+filename, 'rb') as handle:
        savedData[key]= pickle.load(handle)

In [3]:
for key in savedData:
    print key
    numChips= []
    for i in range(len(savedData[key]['obsHistID'])):
        numChips.append(len(savedData[key]['chipNames'][i]))
    print '-- Max number of chips added by any given visit: %d'%(max(numChips))
    print '-- Min number of chips added by any given visit: %d'%(min(numChips))
    print '-- Total number of chips (across all visits to be simulated): %d\n'%(sum(numChips))

RandomDitherFieldPerVisit_randomRotDithered
-- Max number of chips added by any given visit: 191
-- Min number of chips added by any given visit: 1
-- Total number of chips (across all visits to be simulated): 131052

NoDither
-- Max number of chips added by any given visit: 196
-- Min number of chips added by any given visit: 11
-- Total number of chips (across all visits to be simulated): 207704

RandomDitherFieldPerVisit
-- Max number of chips added by any given visit: 191
-- Min number of chips added by any given visit: 1
-- Total number of chips (across all visits to be simulated): 131004



In [4]:
key= 'RandomDitherFieldPerVisit_randomRotDithered'
savedData[key].keys()

['fIDs', 'chipNames', 'obsHistID', 'expDate']

In [5]:
print np.unique(savedData[key]['fIDs'])
print len(np.unique(savedData[key]['fIDs']))

[1212 1220 1234 1305 1323 1333 1365 1413 1431 1447 1464 1542 1564 1568]
14


In [6]:
# example
zip(savedData[key]['obsHistID'][0:10], savedData[key]['fIDs'][0:10], savedData[key]['chipNames'][0:10])

[(40336,
  array([1305]),
  array(['R:0,1 S:0,0', 'R:0,1 S:0,1', 'R:0,1 S:0,2', 'R:0,2 S:0,0',
         'R:0,2 S:0,1', 'R:0,2 S:0,2', 'R:0,3 S:0,1', 'R:0,3 S:0,2',
         'R:0,3 S:1,1', 'R:0,3 S:1,2', 'R:0,3 S:2,1', 'R:0,3 S:2,2',
         'R:0,4 S:1,0', 'R:0,4 S:2,0,A', 'R:0,4 S:2,0,B', 'R:1,3 S:0,2',
         'R:1,3 S:1,2', 'R:1,4 S:0,0', 'R:1,4 S:1,0', 'R:1,4 S:1,1'], 
        dtype='|S13')),
 (40337,
  array([1323]),
  array(['R:0,0 S:1,2', 'R:0,0 S:2,1', 'R:0,0 S:2,2,A', 'R:0,0 S:2,2,B',
         'R:0,1 S:1,0', 'R:0,1 S:1,1', 'R:0,1 S:1,2', 'R:0,1 S:2,0',
         'R:0,1 S:2,1', 'R:0,1 S:2,2', 'R:0,2 S:1,0', 'R:0,2 S:1,1',
         'R:0,2 S:1,2', 'R:0,2 S:2,0', 'R:0,2 S:2,1', 'R:0,2 S:2,2',
         'R:0,3 S:2,0', 'R:1,0 S:0,0', 'R:1,0 S:0,1', 'R:1,0 S:0,2',
         'R:1,0 S:1,0', 'R:1,0 S:1,1', 'R:1,0 S:1,2', 'R:1,0 S:2,0',
         'R:1,0 S:2,1', 'R:1,0 S:2,2', 'R:1,1 S:0,0', 'R:1,1 S:0,1',
         'R:1,1 S:0,2', 'R:1,1 S:1,0', 'R:1,1 S:1,1', 'R:1,1 S:1,2',
         'R:1,1 S

In [7]:
len(np.unique(savedData[key]['expDate']))

2395

In [8]:
len(np.unique(savedData[key]['obsHistID']))

2395